name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.1
  supabase_flutter: ^2.9.0
  app_links: ^6.4.0  # Updated app_links to a compatible version
  cupertino_icons: ^1.0.8
  fl_chart: ^1.0.0
  http: ^1.4.0
  uni_links: ^0.5.1
  logger: ^2.5.0
  image_picker: ^1.0.4
  path: ^1.8.3
  google_fonts: ^6.2.1  
 
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0  

flutter:
  uses-material-design: true

  assets:
    - assets/images/SereneMind Logo.png
    - assets/images/run.jpg
    - assets/images/profile.png